### ISSUE TITLE
Enhance the random map generation

### ISSUE THREAD

**Issue by WGierke** [sleighsoft/genetic-gaming#10]
- [x] Allow saving of seed to restore the map
- [x] Add back loading of a pre-designed map as an alternative to generated one
- [x] Add a camera that follows the first car, so we can generate endless tracks.

**Comment by WGierke** [comment]
Saving the map seed has been added in fa164bad54700656f7c957fec02a8c9bf0c19cab

**Comment by sleighsoft** [comment]
@Raandom Can you do that part with the camera until next week?

**Comment by sleighsoft** [comment]
@Raandom Can this be closed?
