### ISSUE TITLE
Implement "RunSaver"

### ISSUE THREAD

**Issue by sleighsoft** [sleighsoft/genetic-gaming#15]
This saver should save everything that is specific to a run in a single directory to allow reproducible runs.

This saves:
- Seeds
- Config (including commandline parameter)
- Git commit hash
- Console parameter

**Comment by sleighsoft** [comment]
@WGierke Can you document somewhere how to use it?

**Comment by WGierke** [comment]
Closed via 31b1a61ca33d256bbe10843ccc59da31803ca265
