### ISSUE TITLE
Make fitness function parameters configurable

### ISSUE THREAD

**Issue by sleighsoft** [sleighsoft/genetic-gaming#23]

**Comment by Raandom** [comment]
Done. Hab dabei mal ne neue "mixed" fitness function eingeführt (bekommt 2 fitness functions + gewichte als parameter), die als ersatz für fap und close+path dient. Hab dabei die vorkonfigurierten configs angepasst. Wenn ihr noch selber andere habt müsstet ihr die jetzt auch anpassen.
