### ISSUE TITLE
Remove error messages on SIGKILL

### ISSUE THREAD

**Issue by Raandom** [sleighsoft/genetic-gaming#35]
Could we remove the annoying error message that raises on CMD+C? I think a simple try, catch, ignore should be able to solve that.

**Comment by sleighsoft** [comment]
Then do it: https://stackoverflow.com/questions/1112343/how-do-i-capture-sigint-in-python

**Comment by Raandom** [comment]
Done :) Thanks for the Link, basically just copied the code.
