### ISSUE TITLE
Generate a random map

### ISSUE THREAD

**Issue by WGierke** [sleighsoft/genetic-gaming#5]

**Comment by sleighsoft** [comment]
1. Add a camera that follows the first car, so we can generate endless tracks.
2. Allow saving of seed to restore map.
3. Add back loading of a pre-designed map as an alternative to generated one

**Comment by Raandom** [comment]
Done with 3.

**Comment by Raandom** [comment]
Aaaaand added Seed-Usage Output and ability to re-enter it later on (See config).

**Comment by WGierke** [comment]
Moving the enhancement requests to another issue since the initial request that is represented by this issue has been fulfilled in 94b23443660ec0e030c01d78798b60fb9335711f
